# Jekyll configuration

name: Alessandro
description: Just my blog

# url is currently only used only for the RSS feed in feed.xml
url: http://darugnaa.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
# baseurl: /jekyll-clean
baseurl: ''

# This can be '' to hide the Github nav button
# github: 'scotte/jekyll-clean'
github: 'darugnaa'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-71316004-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title
gems: [jekyll-paginate]
paginate: 5

highlighter: rouge
markdown: kramdown

exclude: ['README.md', 'LICENSE']
